name: Python Selenium Tests

on:
  push:
    branches: [master]  # Change to your default branch if necessary
  pull_request:
    branches: [master]  # Change to your default branch if necessary

jobs:
  test:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' or 'macos-latest'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure `selenium` is included in requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Compatible ChromeDriver
        run: |
          # Get the installed Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | head -n 1)
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)

          # Get the corresponding ChromeDriver version
          CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
          
          # Check if the ChromeDriver version exists before downloading
          if [ -z "$CHROME_DRIVER_VERSION" ]; then
            echo "No ChromeDriver version found for Chrome $CHROME_VERSION. Exiting."
            exit 1
          fi

          wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip" -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Tests
        env:
          DISPLAY: ":99.0"  # Required for headless mode on Linux
        run: python Senario_1.py  # Run your Python script
